services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: zuke-dev
    container_name: zuke-dev
    volumes:
      - ${PWD}:/app
      - node_modules:/app/node_modules
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - ZUKE_S3_DEFAULT_ENDPOINT_URL=http://localhost:9000
      - ZUKE_S3_DEFAULT_BUCKET_NAME=zuke-test-bucket
      - ZUKE_S3_DEFAULT_ACCESS_KEY_ID=
      - ZUKE_S3_DEFAULT_SECRET_ACCESS_KEY=
      - ZUKE_S3_DEFAULT_HTTP_PROXY=
    restart: on-failure
    working_dir: /app
    command: [ "sleep", "infinity" ]

volumes:
  node_modules:
