version: "3"
services:
  app:
    image: ghcr.io/dbcls/zuke:0.1.0
    container_name: zuke
    ports:
      - 0.0.0.0:3000:3000
    restart: on-failure
    working_dir: /app
    entrypoint: ["tini", "--"]
    command: [ "npm", "run", "serve"]
