services:
  minio:
    # https://hub.docker.com/r/minio/minio/tags
    image: minio/minio:RELEASE.2024-07-29T22-14-52Z
    container_name: zuke-minio-dev
    environment:
      - MINIO_ROOT_USER=zuke-admin-user
      - MINIO_ROOT_PASSWORD=zuke-admin-password
    volumes:
      - ${PWD}/minio-data:/data
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9001:9001
    restart: on-failure
    command: ["server", "/data", "--console-address", ":9001"]
