version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: zuke-dev
    container_name: zuke-dev
    volumes:
      - ${PWD}:/app
      - node_modules:/app/node_modules
    ports:
      - 127.0.0.1:3000:3000
    restart: on-failure
    working_dir: /app
    entrypoint: ["tini", "--"]
    command: [ "sleep", "infinity" ]

volumes:
  node_modules:
