name: release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release_docker_image:
    if: github.repository == 'dbcls/backup-system'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/zuke:latest
            ghcr.io/${{ github.repository_owner }}/zuke:${{ github.ref_name }}

  create_gh_release:
    if: github.repository == 'dbcls/backup-system'
    runs-on: ubuntu-22.04
    steps:
      - name: Create Release
        run: |
          gh release \
            --repo ${{ github.repository }} \
            create ${{ github.ref_name }} \
            --title ${{ github.ref_name }} \
            --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_gh_pages:
    if: github.repository == 'dbcls/backup-system'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: ZUKE_BASE_URL=/backup-system/ npm run build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
